### ISSUE TITLE
Does not show menu on phone without menu button

### ISSUE THREAD

**Issue by nielsswinkels** [iisy/SmartObjectRecognition#1]
Just to let you know, this app is unusable on a phone that does not have a physical menu button. Usually apps that make use of such menus would show a (...) button somewhere on the screen if the phone does not have a physical menu button, but your app somehow does not do this.

**Comment by micheleAlberto** [comment]
I am also having the same problem on a nexus 4 . 
I am new to android development but on http://developer.android.com/guide/topics/ui/menus.html: 
<If you've developed your application for Android 3.0 (API level 11) and higher, items from the options menu are available in the app bar. By default, the system places all items in the action overflow, which the user can reveal with the action overflow icon on the right side of the app bar (or by pressing the device Menu button, if available). To enable quick access to important actions, you can promote a few items to appear in the app bar by adding android:showAsAction="ifRoom" to the corresponding <item> elements (see figure 2).
For more information about action items and other app bar behaviors, see the Adding the App Bar training class.>

So i guess you developed for your phone that has a physical menu button. The same page link a tutorial on how to add an app bar where the menu element should be shown.

**Comment by iisy** [comment]
Thanks for Report. I will upload a new app called "Smart OR2" into the Google Play Store in the next few hours. The new app will have the desired Feature.

Download it: https://play.google.com/store/apps/details?id=net.iisy.dmatcher
