### ISSUE TITLE
processDebugResources Error

### ISSUE THREAD

**Issue by prateep03** [iisy/SmartObjectRecognition#2]
Hi, 

  I found this line in your res/menu/menu_main.xml:148

    < item android:id="@+id/ matcher" android:title="Matcher" >

  I tried building your code in Android Studio with opencv 2.4.10 and faced "processDebugResources java.lang.IllegalArgumentException" compilation error because of the "@+id/ matcher". Is this really a typo or any problem with the way I built your code ? Thanks a lot for your help.

Prateep

**Comment by FayZi** [comment]
remove space while defining id of item.

< item android:id="@+id/ matcher" android:title="Matcher" >

**Comment by iisy** [comment]
Hi, 
Unfortunately, I have not run the code yet on AndroidStudio.
Please try the suggested solution from FayZi.
I think this should solve the problem.

**Comment by prateep03** [comment]
I fixed the issue as FayZi said. I thought this was a bug and hence reported as issue. Thanks for the confirmation iisy.
